### ISSUE TITLE
New Resource: Training in the Open

### ISSUE THREAD

**Issue by emmajane** [stagefright/stagefright.github.io#13]
I would like to propose that my own site, Training in the Open, be included. The most relevant section is at: http://trainingintheopen.com/speaker-training/. And the most popular page to date has been the speakers checklist: http://trainingintheopen.com/speakers-checklist.html; however, many people have told me that the recordings from past DrupalCon "speaker training" sessions have been very useful to them. These are available from: http://trainingintheopen.com/delivery/speaker-training-drupalcon.html.

**Comment by loonytoons** [comment]
Awesome, thanks emmajane! I'll get these added as soon as I can :-)
